### ISSUE TITLE
KaitaiStream must have ability to report position relative to root IO object

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct_java_runtime#26]
That absolute positions must be stored in the debug maps (`_attrStart`, `_attrEnd`, `_arrStart`, `_arrEnd`). Without that it is impossible or too hard to determine correct position of parsed objects, especially of `instances` objects.

For example, consider following KSY:
```yaml
meta:
  id: offsets
seq:
  - id: padding
    type: u1
  - id: unsized
    type: type
  - id: sized
    type: type
    size: 10
types:
  type:
    seq:
      - id: padding
        type: u1
      - id: unsized_simple
        type: u1
      - id: sized_simple
        size: 1
      - id: unsized_array
        type: elem
        repeat: expr
        repeat-expr: 2
      - id: sized_array
        type: elem
        size: 3
        repeat: expr
        repeat-expr: 1
  elem:
    seq:
      - id: padding
        type: u1
      - id: value
        type: u1
```
The following problem is currently being observed:
This show correct location
![Type](https://user-images.githubusercontent.com/450131/74091177-a03c8900-4ad6-11ea-9869-3f9a9c9d96fd.png)
That location is wrong, must be inside previous region:
![Content](https://user-images.githubusercontent.com/450131/74091173-93b83080-4ad6-11ea-88f0-9cac89bd80d5.png)
